"""add password to user

Revision ID: 083936ae683e
Revises: 
Create Date: 2024-11-18 15:15:48.931811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083936ae683e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
