"""added username

Revision ID: 536a009e49d5
Revises: 7c9472ee73b9
Create Date: 2024-11-27 18:31:34.538467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536a009e49d5'
down_revision = '7c9472ee73b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
